### ISSUE TITLE
Caused by: java.lang.RuntimeException this reader only responds to

### ISSUE THREAD

**Issue by mystdeim** [neuland/jade4j#150]
I got this error:

```
Caused by: java.lang.RuntimeException: this reader only responds to [/home/user/project/build/resources/main/views/layout.jade] templates
	at de.neuland.jade4j.template.ReaderTemplateLoader.checkName(ReaderTemplateLoader.java:31)
	at de.neuland.jade4j.template.ReaderTemplateLoader.getReader(ReaderTemplateLoader.java:25)
```

My template:

```
extends ../layout

block content
    h1= context.title
    p Welcome to our test
```

What does this error mean?

**Comment by Ereldev** [comment]
I have the same issue, any info to solve it ?

**Comment by gijoerg** [comment]
You should not reference other templates in your template if using ReaderTemplateLoader, because multiple template loaders are currently not supported. Maybe you could use a FileTemplateLoader?

The exception message in 1.2.8 will transport this information.

**Comment by gijoerg** [comment]
PR #183 is ready for review.

**Comment by chbloemer** [comment]
Should be fine for now.
