### ISSUE TITLE
Hey,jade4j could not understand //- comment

### ISSUE THREAD

**Issue by magixsource** [neuland/jade4j#89]
jade file like
https://github.com/magixsource/questionbank/blob/master/views/about.jade

and this jade work well on nodejs,but use jade4j in java env

Exception in thread "main" class de.neuland.jade4j.exceptions.JadeLexerException index.jade:10
invalid indentation; expecting 4 spaces
	at de.neuland.jade4j.lexer.Lexer.indent(Lexer.java:635)
	at de.neuland.jade4j.lexer.Lexer.next(Lexer.java:126)
	at de.neuland.jade4j.lexer.Lexer.lookahead(Lexer.java:166)
	at de.neuland.jade4j.parser.Parser.lookahead(Parser.java:735)
	at de.neuland.jade4j.parser.Parser.peek(Parser.java:739)
	at de.neuland.jade4j.parser.Parser.parseBlock(Parser.java:256)
	at de.neuland.jade4j.parser.Parser.parseExpr(Parser.java:125)
	at de.neuland.jade4j.parser.Parser.parse(Parser.java:97)
	at de.neuland.jade4j.JadeConfiguration.createTemplate(JadeConfiguration.java:84)
	at de.neuland.jade4j.JadeConfiguration.getTemplate(JadeConfiguration.java:56)

**Comment by FinalGuy** [comment]
Hi magixsource, 

i will have a look at it. Thanks for reporting.

**Comment by FinalGuy** [comment]
After a first look it turns out that removing the wrong indented comment block (or indenting it valid) makes the file pass.
